Repository openshift/managed-prometheus-exporter-stuck-ebs-vols, pull requests merged in 2019-05, with the labels that each got.

#11 Updated OWNERS to be consistent with SRE operators
  OWNERS
Labels: lgtm, size/XS

#10 Added selectorsyncset generation
  .gitignore
  Makefile
  project.mk
  scripts/generate_syncset.py
  scripts/templates/selectorsyncset.yaml
Labels: approved, lgtm, size/M

#12 Added all requirements for app-sre pipeline
  .gitignore
  Makefile
  hack/00-osd-managed-prometheus-exporter-stuck-ebs-vols.selectorsyncset.yaml.tmpl
  hack/app_sre_build_deploy.sh
  hack/app_sre_pr_check.sh
  project.mk
  scripts/generate_syncset.py
  scripts/templates/selectorsyncset.yaml
Labels: size/L

#13 made app-sre scripts executable
  hack/app_sre_build_deploy.sh
  hack/app_sre_pr_check.sh
Labels: size/XS

#14 Fix name of selector sync set
  hack/00-osd-managed-prometheus-exporter-stuck-ebs-vols.selectorsyncset.yaml.tmpl
  scripts/templates/selectorsyncset.yaml
Labels: size/XS
