Repository openshift/managed-prometheus-exporter-stuck-ebs-vols, pull requests merged in 2019-03, with the labels that each got.

#1 SREP-923: Move ebs-stuck-volume exporter
  .gitignore
  Makefile
  README.md
  deploy/010_serviceaccount-rolebinding.yaml
  deploy/050_service.yaml
  deploy/060_servicemonitor.yaml
  monitor/main.py
  resources/040_deployment.yaml.tmpl
  resources/secrets-config.tmpl
  resources/secrets-credentials.tmpl
Labels: lgtm, size/L

#3 Move to use origin-cli-based image w/ cred minter & ebs-iops-reporter Makefile format
  .gitignore
  Makefile
  deploy/010_serviceaccount-rolebinding.yaml
  functions.mk
  monitor/start.sh
  resources/010_serviceaccount-rolebinding.yaml.tmpl
  resources/020-awscredentials-request.yaml.tmpl
  resources/040_deployment.yaml.tmpl
  resources/050_service.yaml.tmpl
  resources/060_servicemonitor.yaml.tmpl
  resources/secrets-config.tmpl
  resources/secrets-credentials.tmpl
Labels: size/L

#4 Correct Makefile typo, remove "dev" target
  Makefile
Labels: bug

#5 Ensure the deploy directory exists
  deploy/.gitkeep
Labels: kind/bug, size/XS

#6 Update init container image to redhat quay.io org
  Makefile
Labels: kind/cleanup, size/XS

#7 Update cloudcredential.openshift.io to v1
  resources/020-awscredentials-request.yaml.tmpl
Labels: lgtm, size/XS

#8 Missed AWSProviderSpec version
  resources/020-awscredentials-request.yaml.tmpl
Labels: size/XS

#9 Updated initcontainer to fix CLUSTERID
  Makefile
Labels: size/XS
